[general]
import = ["themes/x.toml"]
live_config_reload = true

[env]
TERM = "alacritty"
COLORTERM = "truecolor"

[window]
opacity = 0.80
decorations = "None"
dynamic_padding = true
padding = { x = 6, y = 6 }

[font]
size = 10.0
normal.family = "Hack Nerd Font"
normal.style = "Regular"
bold.family = "Hack Nerd Font"
bold.style = "Bold"
italic.family = "Hack Nerd Font"
italic.style = "Italic"
bold_italic.family = "Hack Nerd Font"
bold_italic.style = "Bold Italic"

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.12

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]
