import = ["themes/xscriptor-theme.toml"]

live_config_reload = true
ipc_socket = true

[env]
TERM = "alacritty"
COLORTERM = "truecolor"

[window]
opacity = 0.80
decorations = "None"
dynamic_padding = true
padding.x = 6
padding.y = 6
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true

[font]
size = 12.0
normal.family = "AnonymicePro Nerd Font"
normal.style = "Regular"
bold.family = "AnonymicePro Nerd Font"
bold.style = "Bold"
italic.family = "AnonymicePro Nerd Font"
italic.style = "Italic"
bold_italic.family = "AnonymicePro Nerd Font"
bold_italic.style = "Bold Italic"
fallback = ["Symbols Nerd Font", "Noto Color Emoji", "DejaVu Sans Mono"]

[cursor]
style.shape = "Beam"
style.blinking = "On"
thickness = 0.12

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]
