[colors]
foreground = "#f7f1ff"
background = "#140706"
ansi = ["#222222", "#fc618d", "#7bd88f", "#ffed89", "#47e6ff", "#ff9999", "#47e6ff", "#f7f1ff"]
brights = ["#525053", "#fc618d", "#7bd88f", "#ffed89", "#47e6ff", "#ff9999", "#47e6ff", "#f7f1ff"]
cursor_bg = "#f7f1ff"
cursor_fg = "#140706"
cursor_border = "#f7f1ff"
selection_bg = "#2a2a2a"
selection_fg = "#f7f1ff"

