[colors]
foreground = "#544d40"
background = "#f8fafe"
ansi = ["#c0bbae", "#1faa9e", "#733d9a", "#2e70ad", "#b55a0f", "#3e9d21", "#bd4c3d", "#191919"]
brights = ["#b0a999", "#009e91", "#5a1f8a", "#0f5ba2", "#b23b00", "#218c00", "#b32e1f", "#000000"]
cursor_bg = "#544d40"
cursor_fg = "#f8fafe"
cursor_border = "#544d40"
selection_bg = "#e6eef8"
selection_fg = "#544d40"

