[colors]
foreground = "#333333"
background = "#ffffff"
ansi = ["#000000", "#333333", "#444444", "#555555", "#666666", "#777777", "#888888", "#999999"]
brights = ["#333333", "#444444", "#555555", "#666666", "#777777", "#888888", "#999999", "#aaaaaa"]
cursor_bg = "#333333"
cursor_fg = "#ffffff"
cursor_border = "#333333"
selection_bg = "#dddddd"
selection_fg = "#333333"

