[colors]
foreground = "#abb2bf"
background = "#181a1f"
ansi = ["#3f4451", "#e05561", "#8cc265", "#d18f52", "#4aa5f0", "#c162de", "#42b3c2", "#e6e6e6"]
brights = ["#4f5666", "#ff616e", "#a5e075", "#f0a45d", "#4dc4ff", "#de73ff", "#4cd1e0", "#ffffff"]
cursor_bg = "#abb2bf"
cursor_fg = "#181a1f"
cursor_border = "#abb2bf"
selection_bg = "#2a2e34"
selection_fg = "#abb2bf"

